name: YouTube IPTV Guncelleme

on:
  schedule:
    # Her 3 saatte bir otomatik çalışır (UTC saatine göredir)
    - cron: '0 */2 * * *'
  workflow_dispatch: # İstediğiniz zaman manuel tetiklemek için button ekler

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Repoya dosya yazabilme izni

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-python: '3.10'

    - name: Gerekli Kütüphaneleri Yükle ve Güncelle
      run: |
        pip install --upgrade pip
        pip install --upgrade yt-dlp

    - name: DNS Ayarlarını Düzelt (İnterneti Garantiye Al)
      run: |
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf

    - name: Scripti Çalıştır ve Linkleri Topla
      run: python guncelle.py


    - name: Değişiklikleri Repoya Kaydet (Push)
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add liste.m3u
        git diff-index --quiet HEAD || git commit -m "IPTV Listesi Otomatik Güncellendi"
        git push
